# 0 - off
# 1 - warning
# 2 - error

rules:
  # header
  header-case: [2, 'always', 'lower-case']
  header-full-stop: [2, 'never', '.']
  # type
  type-case: [2, 'always', 'lower-case']
  type-empty: [2, 'never']
  type-enum: [2, 'always', [
    'build', 'ci', 'chore', 'docs', 'feat', 'fix', 'perf', 'refactor', 'revert', 'style', 'test'
  ]]
  # scope
  scope-case: [2, 'always', 'lower-case']
  scope-empty: [2, 'never']
  # subject
  subject-case: [2, 'always', 'lower-case']
  subject-empty: [2, 'never']
  subject-full-stop: [2, 'never', '.']
  # body
  body-case: [2, 'always', 'lower-case']
  body-leading-blank: [2, 'always']
  # footer
  footer-leading-blank: [2, 'always']
